flowchart LR

subgraph Pool["Entrega de Atividade"]

subgraph Estudante
A((Início))
B[Acessar Sistema]
C[Selecionar Atividade]
D{Prazo de entrega válido?}
E[Anexar Arquivo]
F[Confirmar Envio]
G[Exibir mensagem: Prazo encerrado]
H((Fim))
end

subgraph Sistema
I[Receber dados do envio]
J[Validar anexo e registrar informações]
K[Salvar no banco de dados (Data e Hora)]
L[Enviar notificação ao professor]
M((Fim))
end

A --> B
B --> C
C --> D

D -- Sim --> E
E --> F
F -.-> I

D -- Não --> G
G --> H

I --> J
J --> K
K --> L
L --> M

end
