@startuml
left to right direction
skinparam packageStyle rectangle

actor "Estudante" as aluno
actor "Professor" as prof
actor "Coordenador" as coord

rectangle "Sistema de Gestão de Sala de Aula Online" {
  usecase "Criar Turma" as UC1
  usecase "Matricular em Turma" as UC2
  usecase "Publicar Material" as UC3
  usecase "Criar Atividade" as UC4
  usecase "Entregar Atividade" as UC5
  usecase "Corrigir Atividade" as UC6
  usecase "Visualizar Notas" as UC7
  usecase "Acompanhar Engajamento" as UC8
  usecase "Receber XP (Gamificação)" as UC9
}

prof --> UC1
prof --> UC3
prof --> UC4
prof --> UC6

aluno --> UC2
aluno --> UC5
aluno --> UC7
aluno --> UC9

coord --> UC8

UC5 .> UC9 : <<include>>
@enduml
